export { default as toFirstUpperCase } from './toFirstUpperCase'
export { default as getPath } from './getPath'
export { default as getComputedStyleNumber } from './getComputedStyleNumber'
export { default as getItemByPath } from './getItemByPath'
export { default as getTemplateValue } from './getTemplateValue'
export { default as getCurrentMenuIndexs } from './getCurrentMenuIndexs'
export { default as toUnicode } from './toUnicode'
